SET SQL_SAFE_UPDATES = 0;
DELETE FROM Section_T;
DELETE FROM CoOfferedCourse_T;
DELETE FROM Course_T;
DELETE FROM Department_T;
DELETE FROM School_T;
DELETE FROM Faculty_T;
DELETE FROM Classroom_T;
SET SQL_SAFE_UPDATES = 1;