# Generated by Django 3.2.7 on 2021-11-20 22:18

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('cSchool_ID', database.models.FixedCharField(max_length=5, primary_key=True, serialize=False)),
                ('cSchoolName', models.CharField(max_length=50)),
            ],
        ),
    ]
