# Generated by Django 3.2.7 on 2021-11-21 10:17

import database.models
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('cRoom_ID', database.models.FixedCharField(max_length=10, primary_key=True, serialize=False)),
                ('nRoomCapacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CoOfferedCourse',
            fields=[
                ('cCoffCode_ID', database.models.FixedCharField(max_length=7, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('cFaculty_ID', database.models.FixedCharField(max_length=4, primary_key=True, serialize=False)),
                ('cFacultyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('cSchool_ID', database.models.FixedCharField(max_length=5, primary_key=True, serialize=False)),
                ('cSchoolName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dYear', database.models.YearField()),
                ('nSectionNumber', models.IntegerField()),
                ('nSectionCapacity', models.PositiveSmallIntegerField()),
                ('nEnrolled', models.PositiveSmallIntegerField()),
                ('bIsBlocked', models.BooleanField()),
                ('tStartTime', database.models.TimeField()),
                ('tEndTime', database.models.TimeField()),
                ('eDays', django_mysql.models.EnumField(choices=[('Sunday and Tuesday', 'St'), ('Monday and Wednesday', 'Mw'), ('Sunday', 'S'), ('Monday', 'M'), ('Tuesday', 'T'), ('Wednesday', 'W'), ('Thursday', 'R'), ('Saturday', 'A'), ('Friday', 'F')])),
                ('eSession', django_mysql.models.EnumField(choices=[('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Spring', 'Spring')])),
                ('cCoffCode_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.coofferedcourse')),
                ('cFaculty_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.faculty')),
                ('cRoom_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('cDepartment_ID', database.models.FixedCharField(max_length=3, primary_key=True, serialize=False)),
                ('cDepartmentName', models.CharField(max_length=50)),
                ('cSchool_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.school')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cCourse_ID', database.models.FixedCharField(max_length=7, primary_key=True, serialize=False)),
                ('cCourseName', models.CharField(max_length=50)),
                ('nCreditHours', models.PositiveSmallIntegerField()),
                ('cDepartment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
            ],
        ),
        migrations.AddField(
            model_name='coofferedcourse',
            name='cCourse_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.course'),
        ),
    ]
