# Generated by Django 3.2.7 on 2021-11-21 08:14

import database.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('cFaculty_ID', database.models.FixedCharField(max_length=4, primary_key=True, serialize=False)),
                ('cFacultyName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('cDepartment_ID', database.models.FixedCharField(max_length=3, primary_key=True, serialize=False)),
                ('cDepartmentName', models.CharField(max_length=50)),
                ('cSchool_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.school')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cCourse_ID', database.models.FixedCharField(max_length=7, primary_key=True, serialize=False)),
                ('cCourseName', models.CharField(max_length=50)),
                ('nCreditHours', models.PositiveSmallIntegerField(max_length=50)),
                ('cDepartment_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
            ],
        ),
    ]
